import enum
class UserDesignation(enum.Enum):
    GRAM_PANCHAYAT_ADHIKARI = "ग्राम पंचायत अधिकारी"
    VISTAR_ADHIKARI = "विस्तार अधिकारी"
    BLOCK_DEVELOPMENT_OFFICER = "ब्लॉक विकास अधिकारी"
    ASSISTANT_ENGINEER = "सहायक अभियंता"
    JUNIOR_ENGINEER = "कनिष्ठ अभियंता"
    ACCOUNTANT = "लेखाकार"
    ASSISTANT_ACCOUNTANT = "सहायक लेखाकार"
    DATA_ENTRY_OPERATOR = "डेटा एंट्री ऑपरेटर"
    OFFICE_ASSISTANT = "कार्यालय सहायक"
    FIELD_ASSISTANT = "मैदान सहायक"
    SUPERVISOR = "पर्यवेक्षक"
    COORDINATOR = "समन्वयक"
    PROJECT_MANAGER = "परियोजना प्रबंधक"
    ADMINISTRATOR = "प्रशासक"
    DIRECTOR = "निदेशक"
    OTHER = "अन्य"