from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer
"""
Revision ID: 2a34e1c5ce77
Revises: 
Create Date: 2025-07-02 11:48:13.557891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a34e1c5ce77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('yojanas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_block_district_name', 'blocks', ['district_id', 'name'], unique=False)
    op.create_index(op.f('ix_blocks_district_id'), 'blocks', ['district_id'], unique=False)
    op.create_index(op.f('ix_blocks_name'), 'blocks', ['name'], unique=False)
    op.create_table('gram_panchayats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gram_panchayat_block_name', 'gram_panchayats', ['block_id', 'name'], unique=False)
    op.create_index(op.f('ix_gram_panchayats_block_id'), 'gram_panchayats', ['block_id'], unique=False)
    op.create_index(op.f('ix_gram_panchayats_name'), 'gram_panchayats', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.Enum('GRAM_PANCHAYAT_ADHIKARI', 'VISTAR_ADHIKARI', name='userdesignation'), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('gram_panchayat_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('documents_uploaded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['gram_panchayat_id'], ['gram_panchayats.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_index(op.f('ix_users_block_id'), 'users', ['block_id'], unique=False)
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_gram_panchayat_id'), 'users', ['gram_panchayat_id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index('ix_books_department_id', 'books', ['department_id'], unique=False)
    op.create_index('ix_books_filename', 'books', ['filename'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index('ix_books_title', 'books', ['title'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_english', sa.String(length=200), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('field_definitions', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gr_number', sa.String(length=50), nullable=False),
    sa.Column('gr_code', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('yojana_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['yojana_id'], ['yojanas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gr_code'),
    sa.UniqueConstraint('gr_number')
    )
    op.create_index('ix_gr_department_id_effective_date', 'grs', ['department_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_grs_department_id'), 'grs', ['department_id'], unique=False)
    op.create_index(op.f('ix_grs_effective_date'), 'grs', ['effective_date'], unique=False)
    op.create_table('user_otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('message_sid', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_userotp_user_id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('language_detected', sa.String(length=10), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pages_book_id', 'pages', ['book_id'], unique=False)
    op.create_index('ix_pages_content_gin', 'pages', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index('ix_pages_page_number', 'pages', ['page_number'], unique=False)
    op.create_table('user_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('field_values', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('admin_comments', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_type_id', name='uq_user_document')
    )
    op.create_index('ix_user_documents_verification_status', 'user_documents', ['verification_status'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_marathi', sa.Boolean(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index('ix_words_marathi', 'words', ['is_marathi'], unique=False)
    op.create_index('ix_words_page_id', 'words', ['page_id'], unique=False)
    op.create_index('ix_words_position', 'words', ['x_position', 'y_position'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    
    # Add this block after table creation
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, Boolean, DateTime
    import datetime

    roles_table = table('roles',
        column('id', Integer),
        column('name', String),
        column('description', String),
        column('created_at', DateTime),
        column('updated_at', DateTime),
        column('is_active', Boolean)
    )

    op.bulk_insert(roles_table, [
        {
            'id': 1,
            'name': 'admin',
            'description': 'Administrator',
            'created_at': datetime.datetime.utcnow(),
            'updated_at': None,
            'is_active': True
        },
        {
            'id': 2,
            'name': 'gramSevak',
            'description': 'Gram Sevak/Village Worker',
            'created_at': datetime.datetime.utcnow(),
            'updated_at': None,
            'is_active': True
        },
        {
            'id': 3,
            'name': 'districtAdmin',
            'description': 'District Administrator',
            'created_at': datetime.datetime.utcnow(),
            'updated_at': None,
            'is_active': True
        },
        {
            'id': 4,
            'name': 'blockAdmin',
            'description': 'Block Administrator',
            'created_at': datetime.datetime.utcnow(),
            'updated_at': None,
            'is_active': True
        }
    ])    



    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index('ix_words_position', table_name='words')
    op.drop_index('ix_words_page_id', table_name='words')
    op.drop_index('ix_words_marathi', table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index('ix_user_documents_verification_status', table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index('ix_pages_page_number', table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_index('ix_pages_content_gin', table_name='pages', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_index('ix_pages_book_id', table_name='pages')
    op.drop_table('pages')
    op.drop_table('user_otps')
    op.drop_index(op.f('ix_grs_effective_date'), table_name='grs')
    op.drop_index(op.f('ix_grs_department_id'), table_name='grs')
    op.drop_index('ix_gr_department_id_effective_date', table_name='grs')
    op.drop_table('grs')
    op.drop_table('document_types')
    op.drop_index('ix_books_title', table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index('ix_books_filename', table_name='books')
    op.drop_index('ix_books_department_id', table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_gram_panchayat_id'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_index(op.f('ix_users_block_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gram_panchayats_name'), table_name='gram_panchayats')
    op.drop_index(op.f('ix_gram_panchayats_block_id'), table_name='gram_panchayats')
    op.drop_index('ix_gram_panchayat_block_name', table_name='gram_panchayats')
    op.drop_table('gram_panchayats')
    op.drop_index(op.f('ix_blocks_name'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_district_id'), table_name='blocks')
    op.drop_index('ix_block_district_name', table_name='blocks')
    op.drop_table('blocks')
    op.drop_table('yojanas')
    op.drop_table('roles')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
