from app.api.routes.v1 import auth
from  app.api.routes.v1 import blocks
from  app.api.routes.v1 import districts
from  app.api.routes.v1 import document_status
from  app.api.routes.v1 import government_docs
from  app.api.routes.v1 import gram_sevaks
from  app.api.routes.v1 import preset
from  app.api.routes.v1 import profile
from  app.api.routes.v1 import upload
from app.api.routes.v1 import enhanced_profile
from app.api.routes.v1 import health
