"""Update books and page words models

Revision ID: 2f9067aaa1a7
Revises: 3155d25157f7
Create Date: 2025-06-24 17:37:48.340394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9067aaa1a7'
down_revision: Union[str, None] = '3155d25157f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('language_detected', sa.String(length=10), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pages_book_id', 'pages', ['book_id'], unique=False)
    op.create_index('ix_pages_content_gin', 'pages', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index('ix_pages_page_number', 'pages', ['page_number'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_marathi', sa.Boolean(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index('ix_words_marathi', 'words', ['is_marathi'], unique=False)
    op.create_index('ix_words_page_id', 'words', ['page_id'], unique=False)
    op.create_index('ix_words_position', 'words', ['x_position', 'y_position'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    op.add_column('books', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('books', sa.Column('upload_date', sa.DateTime(), nullable=False))
    op.add_column('books', sa.Column('total_pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('author', sa.String(length=300), nullable=True))
    op.create_index('ix_books_filename', 'books', ['filename'], unique=False)
    op.create_unique_constraint(None, 'books', ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_index('ix_books_filename', table_name='books')
    op.drop_column('books', 'author')
    op.drop_column('books', 'total_pages')
    op.drop_column('books', 'upload_date')
    op.drop_column('books', 'filename')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index('ix_words_position', table_name='words')
    op.drop_index('ix_words_page_id', table_name='words')
    op.drop_index('ix_words_marathi', table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index('ix_pages_page_number', table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_index('ix_pages_content_gin', table_name='pages', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_index('ix_pages_book_id', table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###