"""Add dynamic fields to document types and user documents

Revision ID: 3155d25157f7
Revises: 7202f1702596
Create Date: 2025-06-23 16:39:51.964457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3155d25157f7'
down_revision: Union[str, None] = '7202f1702596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('field_definitions', sa.JSON(), nullable=True))
    op.add_column('document_types', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('document_types', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('user_documents', sa.Column('field_values', sa.JSON(), nullable=True))
    op.add_column('user_documents', sa.Column('admin_comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_documents', 'admin_comments')
    op.drop_column('user_documents', 'field_values')
    op.drop_column('document_types', 'instructions')
    op.drop_column('document_types', 'category')
    op.drop_column('document_types', 'field_definitions')
    # ### end Alembic commands ###