// In your constants file
export const userDesignations = [
  { designationId: 1, designationName: "ग्राम पंचायत अधिकारी" },
  { designationId: 2, designationName: "विस्तार अधिकारी" },
  { designationId: 3, designationName: "ब्लॉक विकास अधिकारी" },
  { designationId: 4, designationName: "सहायक अभियंता" },
  { designationId: 5, designationName: "कनिष्ठ अभियंता" },
  { designationId: 6, designationName: "लेखाकार" },
  { designationId: 7, designationName: "सहायक लेखाकार" },
  { designationId: 8, designationName: "डेटा एंट्री ऑपरेटर" },
  { designationId: 9, designationName: "कार्यालय सहायक" },
  { designationId: 10, designationName: "मैदान सहायक" },
  { designationId: 11, designationName: "पर्यवेक्षक" },
  { designationId: 12, designationName: "समन्वयक" },
  { designationId: 13, designationName: "परियोजना प्रबंधक" },
  { designationId: 14, designationName: "प्रशासक" },
  { designationId: 15, designationName: "निदेशक" },
  { designationId: 16, designationName: "अन्य" }
];

export const docTypeDetails = [
  {
    docTypeId: 1,
    docName: "शासन निर्णय",
  },
  {
    docTypeId: 2,
    docName: "कायदेविषयक पुस्तके",
  },
];

export const documentMasterList = [
  {
    id: 1,
    marathiName: "फोटो",
    englishName: "Photo",
    required: true,
    fields: [],
  },
  {
    id: 2,
    marathiName: "आधार कार्ड",
    englishName: "Adhar Card",
    required: true,
    fields: [
      {
        type: "text",
        name: "adhar_card",
        label: "आधार कार्ड तपशील",
        placeholder: "१२ अंकी आधार क्रमांक",
        required: true,
      },
    ],
  },
  {
    id: 3,
    marathiName: "पॅन कार्ड",
    englishName: "Pan Card",
    required: true,
    fields: [
      {
        type: "text",
        name: "pan_card",
        label: "पॅन कार्ड तपशील",
        placeholder: "ABCDE1234F",
        required: true,
      },
    ],
  },
  {
    id: 4,
    marathiName: "रेशन कार्ड प्रत",
    englishName: "Ration Card Copy",
    required: true,
    fields: [
      {
        type: "text",
        name: "ration_card_copy",
        label: "रेशन कार्ड प्रत तपशील",
        placeholder: "रेशन कार्ड प्रत तपशील",
        required: true,
      },
    ],
  },
  {
    id: 5,
    marathiName: "जन्म प्रमाणपत्र",
    englishName: "Birth Certificate",
    required: false,
    fields: [],
  },
  {
    id: 6,
    marathiName: "जात प्रमाणपत्र",
    englishName: "Caste Certificate",
    required: false,
    fields: [
      {
        type: "text",
        name: "caste_certificate_number",
        label: "जात प्रमाणपत्र तपशील",
        placeholder: "जात प्रमाणपत्र तपशील",
        // required: true,
      },
    ],
  },
  {
    id: 7,
    marathiName: "जात वैधता प्रमाणपत्र",
    englishName: "Caste Validation Certificate",
    required: false,
    fields: [
      {
        type: "text",
        name: "cast_validity_number",
        label: "जात वैधता प्रमाणपत्र तपशील",
        placeholder: "जात वैधता प्रमाणपत्र तपशील",
        // required: true,
      },
    ],
  },
  {
    id: 8,
    marathiName: "पासपोर्ट",
    englishName: "Passport",
    required: false,
    fields: [
      {
        type: "text",
        name: "passport_number",
        label: "पासपोर्ट तपशील",
        placeholder: "पासपोर्ट तपशील",
        // required: true,
      },
    ],
  },
  {
    id: 9,
    marathiName: "एसएससी गुणपत्रक",
    englishName: "SSC Marklist",
    required: true,
    fields: [
      {
        type: "text",
        name: "ssc_marklist",
        label: "एसएससी गुणपत्रक तपशील",
        placeholder: "एसएससी %गुण",
        required: true,
      },
      {
        type: "text",
        name: "ssc_passout_year",
        label: "एसएससी पासआउट वर्ष",
        placeholder: "उदा. २०१२",
        required: true,
      },
    ],
  },
  {
    id: 10,
    marathiName: "एसएससी प्रमाणपत्र",
    englishName: "SSC Certificate",
    required: false,
    fields: [],
  },
  {
    id: 11,
    marathiName: "एचएससी गुणपत्रक",
    englishName: "HSC Marklist",
    required: false,
    fields: [
      {
        type: "text",
        name: "hsc_marklist",
        label: "एचएससी गुणपत्रक तपशील",
        placeholder: "एचएससी %गुण",
        required: true,
      },
      {
        type: "text",
        name: "hsc_passout_year",
        label: "एचएससी पासआउट वर्ष",
        placeholder: "उदा. २०१२",
        required: true,
      },
    ],
  },
  {
    id: 12,
    marathiName: "एचएससी प्रमाणपत्र",
    englishName: "HSC Certificate",
    required: false,
    fields: [],
  },
  {
    id: 13,
    marathiName: "शाळा सोडल्याचा दाखला/टीसी",
    englishName: "Leaving Certificate",
    required: true,
    fields: [],
  },
  {
    id: 14,
    marathiName: "डिप्लोमा गुणपत्रक",
    englishName: "Diploma Marklist",
    required: false,
    fields: [],
  },
  {
    id: 15,
    marathiName: "डिप्लोमा प्रमाणपत्र",
    englishName: "Diploma Certificate",
    required: false,
    fields: [],
  },
  {
    id: 16,
    marathiName: "पदवी गुणपत्रक",
    englishName: "Degree Marklist",
    required: false,
    fields: [],
  },
  {
    id: 17,
    marathiName: "पदवी प्रमाणपत्र",
    englishName: "Degree Certificate",
    required: false,
    fields: [],
  },
  {
    id: 18,
    marathiName: "पदव्युत्तर गुणपत्रक",
    englishName: "PG Marklist",
    required: false,
    fields: [],
  },
  {
    id: 19,
    marathiName: "पदव्युत्तर प्रमाणपत्र",
    englishName: "PG Certificate",
    required: false,
    fields: [],
  },
  {
    id: 20,
    marathiName: "PhD गुणपत्रक",
    englishName: "PhD Marklist",
    required: false,
    fields: [],
  },
  {
    id: 21,
    marathiName: "PhD प्रमाणपत्र",
    englishName: "PhD Certificate",
    required: false,
    fields: [],
  },
  {
    id: 22,
    marathiName: "MS-CIT",
    englishName: "MS-CIT Certificate",
    required: false,
    fields: [],
  },
  {
    id: 23,
    marathiName: "परीक्षेचे हॉल तिकीट",
    englishName: "Hall Ticket of Exam",
    required: false,
    fields: [],
  },
  {
    id: 24,
    marathiName: "निवड आदेश",
    englishName: "Selection Order",
    required: true,
    fields: [],
  },
  {
    id: 25,
    marathiName: "उपस्थिती अर्ज",
    englishName: "Application of Presence",
    required: false,
    fields: [],
  },
  {
    id: 26,
    marathiName: "पगार बँक खाते पासबुक",
    englishName: "Salary Bank Passbook",
    required: true,
    fields: [],
  },
  {
    id: 27,
    marathiName: "ओळखपत्र",
    englishName: "Identity Card",
    required: true,
    fields: [],
  },
  {
    id: 28,
    marathiName: "स्थायी आदेश",
    englishName: "Permanent Order",
    required: false,
    fields: [],
  },
  {
    id: 29,
    marathiName: "सेवा परीक्षा उत्तीर्ण आदेश",
    englishName: "Service Exam Passed Order",
    required: false,
    fields: [],
  },
  {
    id: 30,
    marathiName: "स्थायित्व लाभाचा आदेश",
    englishName: "Confirmation Order",
    required: false,
    fields: [],
  },
  {
    id: 31,
    marathiName: "१२ वर्षे सेवा - प्रगती योजना आदेश",
    englishName: "12 Yrs Sevantrgat Order",
    required: false,
    fields: [],
  },
  {
    id: 32,
    marathiName: "१४ वर्षे सेवा - प्रगती योजना आदेश",
    englishName: "14 Yrs Sevantrgat Order",
    required: false,
    fields: [],
  },
  {
    id: 33,
    marathiName: "१० वर्षे - सुदारित सेवा प्रगती योजना आदेश",
    englishName: "10 Yrs-Sudharit Order",
    required: false,
    fields: [],
  },
  {
    id: 34,
    marathiName: "२० वर्षे - सुदारित सेवा प्रगती योजना आदेश",
    englishName: "20 Yrs-Sudharit Order",
    required: false,
    fields: [],
  },
  {
    id: 35,
    marathiName: "३० वर्षे - सुदारित सेवा प्रगती योजना आदेश",
    englishName: "30 Yrs-Sudharit Order",
    required: false,
    fields: [],
  },
  {
    id: 36,
    marathiName: "उत्कृष्ट/अतिउत्कृष्ट वेतनवाढ आदेश",
    englishName: "Utkrusht Increment Order",
    required: false,
    fields: [],
  },
  {
    id: 37,
    marathiName: "आदर्श ग्रामसेवक पुरस्कार आदेश",
    englishName: "Adarsh Gramsevak Order",
    required: false,
    fields: [],
  },
  {
    id: 38,
    marathiName: "आदर्श ग्रामसेवक पुरस्कार वेतनवाढ आदेश",
    englishName: "Adarsh Gramsevak Increment",
    required: false,
    fields: [],
  },
  {
    id: 39,
    marathiName: "सेवा पुस्तिका प्रती",
    englishName: "Service Book Copy",
    required: false,
    fields: [],
  },
  {
    id: 40,
    marathiName: "बदली आदेश",
    englishName: "Promotion Order",
    required: false,
    fields: [],
  },
  {
    id: 41,
    marathiName: "जिल्हा बदली आदेश (नOCsह)",
    englishName: "District Transfer Order",
    required: false,
    fields: [],
  },
  {
    id: 42,
    marathiName: "मान्यता प्रमाणपत्र",
    englishName: "Consent Certificate",
    required: false,
    fields: [],
  },
];
