export const userDesignations = [
  {
    designationId: 1,
    designationName: "ग्राम पंचायत अधिकारी",
  },
  {
    designationId: 2,
    designationName: "विस्तार अधिकारी",
  },
];

export const docTypeDetails = [
  {
    docTypeId: 1,
    docName: "शासन निर्णय",
  },
  {
    docTypeId: 2,
    docName: "कायदेविषयक पुस्तके",
  },
];

export const documentMasterList = [
  {
    id: 1,
    marathiName: "फोटो",
    englishName: "Photo",
    fieldType: "none",
    placeholder: "",
    required: true,
  },
  {
    id: 2,
    marathiName: "आधार कार्ड",
    englishName: "Adhar Card",
    fieldType: "text",
    placeholder: "१२ अंकी आधार क्रमांक",
    required: true,
  },
  {
    id: 3,
    marathiName: "पॅन कार्ड",
    englishName: "Pan Card",
    fieldType: "text",
    placeholder: "ABCDE1234F",
    required: true,
  },
  {
    id: 4,
    marathiName: "रेशन कार्ड प्रत",
    englishName: "Ration Card Copy",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 5,
    marathiName: "जन्म प्रमाणपत्र",
    englishName: "Birth Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 6,
    marathiName: "जात प्रमाणपत्र",
    englishName: "Caste Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 7,
    marathiName: "जात वैधता प्रमाणपत्र",
    englishName: "Caste Validation Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 8,
    marathiName: "पासपोर्ट",
    englishName: "Passport",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 9,
    marathiName: "एसएससी गुणपत्रक",
    englishName: "SSC Marklist",
    fieldType: "text",
    placeholder: "एसएससी %गुण",
    required: true,
  },
  {
    id: 10,
    marathiName: "एसएससी प्रमाणपत्र",
    englishName: "SSC Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 11,
    marathiName: "एचएससी गुणपत्रक",
    englishName: "HSC Marklist",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 12,
    marathiName: "एचएससी प्रमाणपत्र",
    englishName: "HSC Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 13,
    marathiName: "शाळा सोडल्याचा दाखला/टीसी",
    englishName: "Leaving Certificate",
    fieldType: "none",
    placeholder: "",
    required: true,
  },
  {
    id: 14,
    marathiName: "डिप्लोमा गुणपत्रक",
    englishName: "Diploma Marklist",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 15,
    marathiName: "डिप्लोमा प्रमाणपत्र",
    englishName: "Diploma Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 16,
    marathiName: "पदवी गुणपत्रक",
    englishName: "Degree Marklist",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 17,
    marathiName: "पदवी प्रमाणपत्र",
    englishName: "Degree Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 18,
    marathiName: "पदव्युत्तर गुणपत्रक",
    englishName: "PG Marklist",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 19,
    marathiName: "पदव्युत्तर प्रमाणपत्र",
    englishName: "PG Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 20,
    marathiName: "PhD गुणपत्रक",
    englishName: "PhD Marklist",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 21,
    marathiName: "PhD प्रमाणपत्र",
    englishName: "PhD Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 22,
    marathiName: "MS-CIT",
    englishName: "MS-CIT Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 23,
    marathiName: "परीक्षेचे हॉल तिकीट",
    englishName: "Hall Ticket of Exam",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 24,
    marathiName: "निवड आदेश",
    englishName: "Selection Order",
    fieldType: "none",
    placeholder: "",
    required: true,
  },
  {
    id: 25,
    marathiName: "उपस्थिती अर्ज",
    englishName: "Application of Presence",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 26,
    marathiName: "पगार बँक खाते पासबुक",
    englishName: "Salary Bank Passbook",
    fieldType: "none",
    placeholder: "",
    required: true,
  },
  {
    id: 27,
    marathiName: "ओळखपत्र",
    englishName: "Identity Card",
    fieldType: "none",
    placeholder: "",
    required: true,
  },
  {
    id: 28,
    marathiName: "स्थायी आदेश",
    englishName: "Permanent Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 29,
    marathiName: "सेवा परीक्षा उत्तीर्ण आदेश",
    englishName: "Service Exam Passed Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 30,
    marathiName: "स्थायित्व लाभाचा आदेश",
    englishName: "Confirmation Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 31,
    marathiName: "१२ वर्षे सेवा - प्रगती योजना आदेश",
    englishName: "12 Yrs Sevantrgat Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 32,
    marathiName: "१४ वर्षे सेवा - प्रगती योजना आदेश",
    englishName: "14 Yrs Sevantrgat Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 33,
    marathiName: "१० वर्षे - सुदारित सेवा प्रगती योजना आदेश",
    englishName: "10 Yrs-Sudharit Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 34,
    marathiName: "२० वर्षे - सुदारित सेवा प्रगती योजना आदेश",
    englishName: "20 Yrs-Sudharit Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 35,
    marathiName: "३० वर्षे - सुदारित सेवा प्रगती योजना आदेश",
    englishName: "30 Yrs-Sudharit Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 36,
    marathiName: "उत्कृष्ट/अतिउत्कृष्ट वेतनवाढ आदेश",
    englishName: "Utkrusht Increment Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 37,
    marathiName: "आदर्श ग्रामसेवक पुरस्कार आदेश",
    englishName: "Adarsh Gramsevak Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 38,
    marathiName: "आदर्श ग्रामसेवक पुरस्कार वेतनवाढ आदेश",
    englishName: "Adarsh Gramsevak Increment",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 39,
    marathiName: "सेवा पुस्तिका प्रती",
    englishName: "Service Book Copy",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 40,
    marathiName: "बदली आदेश",
    englishName: "Promotion Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 41,
    marathiName: "जिल्हा बदली आदेश (नOCsह)",
    englishName: "District Transfer Order",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
  {
    id: 42,
    marathiName: "मान्यता प्रमाणपत्र",
    englishName: "Consent Certificate",
    fieldType: "none",
    placeholder: "",
    required: false,
  },
];
